### ISSUE TITLE
LSTM 소스에서 질문이 있습니다^^

### ISSUE THREAD

**Issue by treejw** [DonghyungKo/naver_movie_review_sentiment_classification#1]
=

**Comment by YunNaYoung** [comment]
def sort_by_sequence_length(self, x, y, seq_len):
sorted_idx = np.argsort(np.array(seq_len))[::-1]
x = Variable(torch.LongTensor(np.array(x)[sorted_idx]))
y = Variable(torch.LongTensor(np.array(y)[sorted_idx]))
seq_len = Variable(torch.LongTensor(np.array(seq_len)[sorted_idx]))

함수에서 자꾸 아래와 같은 에러가 나는데..
TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: double, float, float16, int64, int32, and uint8.

해결할 방법이 없을까요..?
numpy to tensor를 하려고 torch.from_numpy로 바꿔봤는데도 같은 에러가 뜹니다..ㅠㅠㅜ
